import React, { useState } from 'react';
import { ArrowLeft, Radio, ArrowRight, AlertCircle, Loader2 } from 'lucide-react';
import { getMatchState, trackSpectatorJoin } from '../lib/supabase';
import type { MatchData } from '../types';

interface Props {
  onBack: () => void;
  onJoinedMatch: (match: MatchData) => void;
}

export const JoinMatchScreen: React.FC<Props> = ({ onBack, onJoinedMatch }) => {
  const [code, setCode] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleJoin = async (e: React.FormEvent) => {
    e.preventDefault();
    const formattedCode = code.trim().toUpperCase();
    if (formattedCode.length < 6) return;

    setLoading(true);
    setError(null);

    const match = await getMatchState(formattedCode);

    setLoading(false);

    if (match) {
      await trackSpectatorJoin(formattedCode);
      onJoinedMatch(match);
    } else {
      setError(`No match found with Room Code "${formattedCode}". Please verify code with the umpire.`);
    }
  };

  const isFormValid = code.trim().length >= 6;

  return (
    <div className="flex-1 flex flex-col bg-[#05070D] text-white p-5 select-none font-['Inter'] relative overflow-y-auto">
      {/* Header */}
      <div className="flex items-center gap-3 shrink-0 mb-4">
        <button
          onClick={onBack}
          className="p-2 bg-white/5 border border-white/10 rounded-xl text-gray-400 hover:text-white transition btn-material"
        >
          <ArrowLeft size={20} />
        </button>
        <div>
          <h1 className="text-[28px] font-black text-white tracking-tight leading-none">Join Match</h1>
          <p className="text-xs text-gray-400 mt-1 font-medium">
            Spectator Mode &bull; <span className="text-emerald-400 font-bold">Read Only</span>
          </p>
        </div>
      </div>

      {/* Main Content Vertically Centered */}
      <div className="flex-1 flex flex-col justify-center items-center max-w-sm mx-auto w-full space-y-6 my-auto py-6">
        {/* Broadcast Stadium Illustration */}
        <div className="relative flex flex-col items-center my-2">
          <div className="w-[140px] h-[140px] rounded-full bg-radial from-blue-600/30 via-blue-900/10 to-transparent border-2 border-blue-500/30 flex items-center justify-center shadow-[0_0_40px_rgba(41,98,255,0.3)]">
            <div className="w-[84px] h-[84px] rounded-full bg-blue-600/20 border border-blue-400/50 flex items-center justify-center text-blue-400 shadow-inner">
              <Radio size={40} className="animate-pulse" />
            </div>
          </div>

          <span className="mt-3 px-4 py-1 bg-blue-600/20 border border-blue-500/40 text-blue-400 font-extrabold text-xs rounded-full uppercase tracking-wider shadow">
            Spectator Mode
          </span>
        </div>

        {/* Enter Room Code Card */}
        <div className="w-full bg-[#111827] border border-white/10 rounded-[20px] p-6 space-y-5 shadow-xl text-center">
          <div>
            <h2 className="text-xl font-bold text-white">Enter Room Code</h2>
            <p className="text-xs text-gray-400 mt-1">
              Enter the 6-character match code generated by the umpire
            </p>
          </div>

          <form onSubmit={handleJoin} className="space-y-4 pt-1">
            <div>
              <label className="text-[11px] font-bold text-gray-400 block text-center uppercase tracking-wider mb-2">
                Room Code (6–8 Characters)
              </label>
              <input
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase())}
                placeholder="ENTER ROOM CODE"
                maxLength={8}
                required
                className="w-full h-[56px] bg-[#05070D] border border-gray-800 focus:border-blue-500 rounded-[18px] px-4 text-center text-xl font-black font-mono tracking-widest text-white placeholder-gray-600 focus:shadow-[0_0_20px_rgba(41,98,255,0.4)] outline-none uppercase transition"
              />
            </div>

            {error && (
              <div className="flex items-start gap-2.5 p-3.5 bg-red-950/40 border border-red-800/60 rounded-xl text-xs text-red-300 text-left">
                <AlertCircle size={16} className="text-red-400 shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Join Button */}
            <button
              type="submit"
              disabled={loading || !isFormValid}
              className="w-full h-[56px] rounded-[18px] bg-gradient-to-r from-blue-600 via-indigo-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 disabled:opacity-40 disabled:pointer-events-none text-white font-black text-base flex items-center justify-center gap-2 shadow-[0_4px_25px_rgba(41,98,255,0.4)] transition btn-material"
            >
              {loading ? (
                <>
                  <Loader2 size={20} className="animate-spin" />
                  <span>Connecting to Stream...</span>
                </>
              ) : (
                <>
                  <span>Join Live Spectator Stream</span>
                  <ArrowRight size={20} />
                </>
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};
