import React, { useEffect, useState } from 'react';
import confetti from 'canvas-confetti';
import { Trophy, Share2, Download, Check, Home, Award, UserCheck, BarChart2 } from 'lucide-react';
import type { MatchData } from '../types';
import { StatCharts } from './StatCharts';
import { TeamCarousel } from './TeamCarousel';

interface Props {
  match: MatchData;
  onDone: () => void;
}

export const MatchFinishedScreen: React.FC<Props> = ({ match, onDone }) => {
  const [copied, setCopied] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<'summary' | 'stats'>('summary');

  useEffect(() => {
    try {
      confetti({
        particleCount: 140,
        spread: 100,
        origin: { y: 0.5 },
        colors: ['#FFB300', '#2962FF', '#00C853', '#FFFFFF']
      });
    } catch (e) {}
  }, []);

  const handleShare = () => {
    const text = `🏆 BSC MATCH RESULT 🏆\n\n${match.matchName} (${match.tournamentName})\n${match.resultSummary}\n\n1st Innings (${match.teamA}): ${match.scoreA}/${match.wicketsA} (${match.oversA} ov)\n2nd Innings (${match.teamB}): ${match.scoreB}/${match.wicketsB} (${match.oversB} ov)\n\nScored on BSC Box Cricket Score Counter.`;

    if (navigator.share) {
      navigator.share({
        title: 'Match Result - BSC',
        text
      }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadScorecard = () => {
    const scorecardText = `=====================================\n        BSC MATCH SCORECARD          \n=====================================\nTournament: ${match.tournamentName}\nMatch: ${match.matchName}\nGround: ${match.ground}\nRoom Code: ${match.roomCode}\n\nRESULT: ${match.resultSummary}\nWINNER: ${match.winnerTeam}\n\nINNINGS 1 (${match.teamA}):\nScore: ${match.scoreA}/${match.wicketsA} in ${match.oversA} overs\n\nINNINGS 2 (${match.teamB}):\nScore: ${match.scoreB}/${match.wicketsB} in ${match.oversB} overs\n=====================================\nGenerated by BSC Box Cricket Score Counter`;

    const blob = new Blob([scorecardText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BSC_Scorecard_${match.roomCode}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 flex flex-col justify-between bg-[#05070D] text-white p-5 select-none overflow-y-auto font-['Inter'] relative">
      {/* Trophy Header Banner */}
      <div className="flex flex-col items-center text-center pt-3 pb-2 animate-scale-up">
        <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-amber-500 via-yellow-400 to-amber-600 p-1 shadow-[0_0_50px_rgba(255,179,0,0.5)] mb-3 flex items-center justify-center">
          <div className="w-full h-full rounded-full bg-[#111827] flex items-center justify-center">
            <Trophy size={48} className="text-amber-400 animate-bounce" />
          </div>
        </div>

        <span className="px-3 py-1 bg-emerald-500/20 text-emerald-400 border border-emerald-500/40 text-xs font-bold rounded-full uppercase tracking-widest mb-1">
          MATCH CONCLUDED
        </span>
        <h2 className="text-2xl font-black font-['Poppins'] text-white my-1">{match.winnerTeam || 'Match Completed'}</h2>

        {/* Signature Accent Sweep Underline */}
        <div className="accent-line mx-auto" />

        <p className="text-sm font-extrabold text-amber-400 mt-1">{match.resultSummary || 'Great box cricket match!'}</p>
      </div>

      {/* Tab Selector: Summary vs Analytics */}
      <div className="flex bg-white/5 p-1 rounded-2xl border border-white/10 my-2">
        <button
          onClick={() => setActiveTab('summary')}
          className={`flex-1 py-2 rounded-xl text-xs font-bold transition ${
            activeTab === 'summary'
              ? 'bg-blue-600 text-white shadow'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          Match Summary
        </button>
        <button
          onClick={() => setActiveTab('stats')}
          className={`flex-1 py-2 rounded-xl text-xs font-bold transition flex items-center justify-center gap-1.5 ${
            activeTab === 'stats'
              ? 'bg-blue-600 text-white shadow'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          <BarChart2 size={14} /> Analytics &amp; Graphs
        </button>
      </div>

      {activeTab === 'summary' ? (
        /* Match Summary Cards */
        <div className="my-2 space-y-3">
          {/* Swipeable Team Carousel Final Summary */}
          <div className="glass p-4 rounded-[22px]">
            <div className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2 text-center">
              Swipe Team Scorecards
            </div>
            <TeamCarousel
              teamA={{
                name: match.teamA,
                sub: `Innings 1 · ${match.scoreA}/${match.wicketsA} (${match.oversA} Overs)`,
                bgGradient: 'linear-gradient(135deg, #2962FF, #00C6FF)'
              }}
              teamB={{
                name: match.teamB,
                sub: `Innings 2 · ${match.scoreB}/${match.wicketsB} (${match.oversB} Overs)`,
                bgGradient: 'linear-gradient(135deg, #9333EA, #C084FC)'
              }}
            />
          </div>

          {/* Award Highlights */}
          <div className="grid grid-cols-2 gap-2.5 pt-1">
            <div className="p-3.5 glass rounded-[20px] flex items-center gap-2.5">
              <div className="p-2 bg-amber-500/20 text-amber-400 rounded-xl shrink-0">
                <Award size={18} />
              </div>
              <div className="truncate min-w-0">
                <span className="text-[9px] text-gray-400 uppercase font-semibold block">TOP SCORER</span>
                <span className="text-xs font-bold text-white truncate block">{match.strikerName}</span>
              </div>
            </div>

            <div className="p-3.5 glass rounded-[20px] flex items-center gap-2.5">
              <div className="p-2 bg-blue-500/20 text-blue-400 rounded-xl shrink-0">
                <UserCheck size={18} />
              </div>
              <div className="truncate min-w-0">
                <span className="text-[9px] text-gray-400 uppercase font-semibold block">BEST BOWLER</span>
                <span className="text-xs font-bold text-white truncate block">{match.bowlerName}</span>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* Analytics Tab */
        <div className="my-2 max-h-72 overflow-y-auto pr-1">
          <StatCharts match={match} />
        </div>
      )}

      {/* Action Buttons */}
      <div className="pt-3 space-y-2.5 shrink-0 border-t border-white/10">
        <div className="flex gap-2">
          <button
            onClick={handleShare}
            className="flex-1 py-3.5 bg-white/5 border border-white/10 hover:bg-white/10 text-white font-bold text-xs rounded-2xl flex items-center justify-center gap-2 transition btn-material"
          >
            {copied ? <Check size={16} className="text-emerald-400" /> : <Share2 size={16} />}
            <span>{copied ? 'Result Copied!' : 'Share Result'}</span>
          </button>
          <button
            onClick={handleDownloadScorecard}
            className="flex-1 py-3.5 bg-white/5 border border-white/10 hover:bg-white/10 text-white font-bold text-xs rounded-2xl flex items-center justify-center gap-2 transition btn-material"
          >
            <Download size={16} />
            <span>Download</span>
          </button>
        </div>

        <button
          onClick={onDone}
          className="w-full py-4 bg-gradient-to-r from-blue-600 via-indigo-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white font-black text-sm rounded-2xl flex items-center justify-center gap-2 shadow-[0_4px_25px_rgba(41,98,255,0.4)] btn-material"
        >
          <Home size={18} />
          <span>Back to Home</span>
        </button>
      </div>
    </div>
  );
};
